version: "3.8"

networks:
  # Specify the network for bridging
  app-network:
    driver: bridge

services:
  netstate:
    build: ./
    depends_on:
      - mysql
    command: yarn run start
    environment:
      NODE_ENV: "production"
      DB_HOST: mysql
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASS}"
      DB_NAME: "${DB_NAME}"
    volumes:
      - "./logs:/app/logs"
    #   - './backend:/app'
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network
  mysql:
    image: mysql:5.7.16
    # image: ibex/debian-mysql-server-5.7
    # Set mysqld charset
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf.d:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    restart: always
    networks:
      - app-network
